### ISSUE TITLE
Support port forwarding

### ISSUE THREAD

**Issue by robd003** [ProtonVPN/ios-mac-app#16]
Could you please add support for port forwarding in the macOS app so that there's feature parity with the Windows app?

**Comment by jaroslavas** [comment]
Thanks for you suggestion. This feature is planned, but unfortunately we don't have ETA.

**Comment by shehackedyou** [comment]
If its planned then why did you close this instead of adding it to some sort of milestone even if not necessarily the next one? 

Seems like you had plenty of time to add a trivial feature; so it appears you really just kicking the can and telling everyone to fuck off in a polite way but since thats apparent it just seems rather disrespectful to the people who use your service.

**Comment by Red6785** [comment]
Adding onto this, the [last blogpost](https://protonvpn.com/blog/product-roadmap-winter-2024-2025) stated that port forwarding would be ready in Winter 2025. It's officially Spring, and, what do we see..? Absolutely nothing. I don't doubt that work is being done but the silence is killing me here, especially considering that port forwarding is the primary reason I chose Proton over Mullvad. At least I could get it working on my Linux desktop with the terminal workaround, but, for macOS, it's just not working, no matter what protocol I use and how many servers I try.

Seriously, please give us SOME information.
